---

- hosts: all
  become: yes
  gather_facts: yes


  vars:

    plone_initial_password: admin

    servers:

      - plone_version: '5.1.2'

        plone_zeo_port: 5100
        plone_client_base_port: 5080
        plone_additional_eggs:
          - collective.recaptcha
          - pas.plugins.authomatic
        plone_sources:
          - "collective.recaptcha = git https://github.com/collective/collective.recaptcha.git rev=tags/2.1.0"
        # plone_buildout_cache_file: /home/steve/ssd/nui5.0/packages/buildout-cache.tar.bz2
        plone_buildout_extra_dir: ./meta/
        plone_client_max_memory: 600MB
        plone_backup_post_command: |
          touch ${buildout:backups-dir}/backups/done
        plone_zodb_cache_size: 10000

      - plone_instance_name: p4
        plone_version: '4.3.17'

        plone_initial_password: admin
        plone_zeo_port: 4100
        plone_additional_eggs:
          - collective.recaptcha
        plone_client_base_port: 4080
        plone_sources:
        plone_extra_parts:
          zopepy: |
            recipe = zc.recipe.egg
            eggs = ${buildout:eggs}
            interpreter = zopepy
            scripts = zopepy

        plone_buildout_extra: |
          allow-picked-versions = false

        plone_additional_versions:
          - "plone4.csrffixes = 1.0.9"
          - "cssselect = 0.9.1"
          - "Products.PloneHotfix20160419 = 1.0"
          - "collective.recaptcha = 2.0"
          - "norecaptcha = 0.3.0"
          - "five.z2monitor = 0.2"
          - "zc.z3monitor = 0.8.0"
          - "zc.monitor = 0.3.1"
          - "zc.ngi = 2.1.0"
          - "collective.recipe.backup = 4.0.1"
          - "plone.recipe.precompiler = 0.6"
          - "plone.recipe.command = 1.1"

        plone_zodb_cache_size_bytes: "512 MB"

        plone_client_max_memory: 500MB

        plone_hot_monitor: no

      - plone_instance_name: no_clients_custom_backup
        plone_zeo_port: 6100
        plone_client_base_port: 6080
        plone_client_count: 0
        plone_backup_path: /var/local/custom_backup_path

      - plone_version: '5.2.1'
        plone_instance_name: p52py27

        plone_zeo_port: 3100
        plone_client_base_port: 3080

      - plone_version: '5.2.1'
        plone_instance_name: p52py3
        plone_python_version: '3'

        plone_zeo_port: 7100
        plone_client_base_port: 7080

        # Not working with python3
        plone_client_tcpcheck: no

  roles:

    - role: ansible.plone_server
      plone_config: "{{ servers[0] }}"
      tags:
        - plone1

    - role: ansible.plone_server
      plone_config: "{{ servers[1] }}"
      tags:
        - plone2

    - role: ansible.plone_server
      plone_config: "{{ servers[2] }}"
      plone_backup_post_command: |
        touch ${buildout:backups-dir}/backups/done
      tags:
        - plone3

    - role: ansible.plone_server
      plone_config: "{{ servers[3] }}"
      tags:
        - plone4

    - role: ansible.plone_server
      plone_config: "{{ servers[4] }}"
      tags:
        - plone5

  tasks:

    # make sure plone daemons have had time to come up
    - pause: minutes=1

    - pip: name=httplib2 extra_args='--index-url=https://pypi.python.org/simple/'

    - name: Check to see if Plone 5 is running
      uri:
        url: http://127.0.0.1:5081/Plone
        method: GET
        status_code: 200
      tags:
        - plone1

    - stat: path=/usr/local/plone-5.1/zeoserver/main.yml
      register: st
      tags:
        - plone1

    - fail: msg="copy of extra dir failed"
      when: not st.stat.exists
      tags:
        - plone1

    - name: Check to see if we copied the extra buildout file
      command: "ls /usr/local/plone-5.1/zeoserver/main.yml"
      tags:
        - plone1

    - name: Attempt a backup for the P5 install
      command: "/usr/local/plone-5.1/zeoserver/bin/backup"
      become_user: plone_daemon
      tags:
        - plone1

    - stat: path=/var/local/plone-5.1/zeoserver/backups/done
      register: st
      tags:
        - plone1
    - fail: msg="Backup 'post' command not executed"
      when: not st.stat.exists
      tags:
        - plone1

    - name: Attempt a restore for the P5 install
      command: "/usr/local/plone-5.1/zeoserver/bin/restore -n"
      become_user: plone_daemon
      tags:
        - plone1

    - name: Attempt a pack for the P5 install
      command: "/usr/local/plone-5.1/zeoserver/bin/zeopack"
      become_user: plone_daemon
      tags:
        - plone1

    - name: Check that we're using superlance in the p5 install (Debian)
      shell: "grep eventlistener {{ supervisor_config_dir }}/zeoserver_zeo.conf"
      when: ansible_os_family != 'Redhat'
      tags:
        - plone1

    - name: Check that we're using superlance in the p5 install (RedHat)
      shell: "grep eventlistener /etc/supervisord.d/zeoserver_zeo.ini"
      when: ansible_os_family == 'RedHat'
      tags:
        - plone1

    - name: Test tcpcheck
      shell: "echo quit | socat -T 1 TCP:127.0.0.1:5181 stdio"
      tags:
        - plone1

    - name: Check to see if Plone 4.3.x is running
      uri:
        url: http://127.0.0.1:4081/Plone
        method: GET
        status_code: 200
      tags:
        - plone2

    - name: Attempt a backup for the P4 install
      command: "/usr/local/plone-4.3/p4/bin/backup"
      become_user: plone_daemon
      tags:
        - plone2

    - name: Attempt a restore for the P4 install
      command: "/usr/local/plone-4.3/p4/bin/restore -n"
      become_user: plone_daemon
      tags:
        - plone2

    - name: Attempt a pack for the P4 install
      command: "/usr/local/plone-4.3/p4/bin/zeopack"
      become_user: plone_daemon
      tags:
        - plone2

    - name: Check that we're not using superlance in the p4 install (Debian)
      shell: "[ ! `grep eventlistener /etc/supervisor/conf.d/p4_zeo.conf` ]"
      when: ansible_os_family != 'Redhat'
      tags:
        - plone2

    - name: Check that we're not using superlance in the p4 install (RedHat)
      shell: "[ ! `grep eventlistener /etc/supervisord.d/p4_zeo.ini` ]"
      when: ansible_os_family == 'RedHat'
      tags:
        - plone2

    - name: Test tcpcheck
      shell: "echo quit | socat -T 1 TCP:127.0.0.1:4181 stdio"
      tags:
        - plone2

    - name: Attempt a backup for the client-less install
      command: "/usr/local/plone-5.2/no_clients_custom_backup/bin/backup"
      become_user: plone_daemon
      tags:
        - plone3

    - stat: path=/var/local/custom_backup_path/no_clients_custom_backup/backups/done
      register: st
      tags:
        - plone3
    - fail: msg="Backup 'post' command not executed"
      when: not st.stat.exists
      tags:
        - plone3

    - name: Attempt a restore for the client-less install
      command: "/usr/local/plone-5.2/no_clients_custom_backup/bin/restore -n"
      become_user: plone_daemon
      tags:
        - plone3

    - name: Check to see if Python 2.7 / Plone 5.2 is running
      uri:
        url: http://127.0.0.1:3081/Plone
        method: GET
        status_code: 200
      tags:
        - plone4

    - name: Check to see if Python 3 / Plone 5.2 is running
      uri:
        url: http://127.0.0.1:7081/Plone
        method: GET
        status_code: 200
      tags:
        - plone5

